### ISSUE TITLE
implement Endpoint for TWINTIP

### ISSUE THREAD

**Issue by drummerwolli** [zalando/spark-appliance#17]
http://stups.readthedocs.org/en/latest/components/twintip.html

if not existing, there are 401 errors all the time ...

**Comment by chutium** [comment]
yes, this issue can make our monitoring tool noisy, and may cause unnecessary alerts.

since we are using connexion framework, and this could be a common issue for other connexion users, i opened an issuse by connexion project https://github.com/zalando/connexion/issues/82, and hope this framework can handle these queries from TWINTIP crawler.

**Comment by hjacobs** [comment]
@chutium @drummerwolli I will take a look at Connexion regarding this issue. We have similar "issues".

**Comment by chutium** [comment]
so it seems this is fixed by https://github.com/zalando/connexion/issues/83 ? at least we will not see 401 errors if we do not have such an endpoint for TWINTIP, should we manually add some dummy contents for this endpoint?
